part 2 was implemented
Mandybur800/StandUpLite pull request #2
Opened 2021-01-29 10:57 UTC by Mandybur800

2021-01-29 12:40 UTC, Max-Pochepets requested changes

2021-01-29 12:40 UTC, Max-Pochepets commented on src/main/java/ua/com/conductor/dao/GenericDao.java
> +public interface GenericDao<T, I> {
You have [functionality](https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_04.html) that is redundant at this state of project, I will list it below. So, for now, let's not use `Generic` interfaces. In fact, you won't be able to use them, or will be forced to change your corresponding interfaces

2021-01-29 12:40 UTC, Max-Pochepets commented on src/main/java/ua/com/conductor/dao/impl/MovieSessionDaoImpl.java
> +                            MovieSession.class);
Test a situation, where some fields of this entity won't be set

2021-01-29 12:40 UTC, Max-Pochepets commented on src/main/java/ua/com/conductor/dao/impl/MovieSessionDaoImpl.java
> +            LocalDateTime end = date.plusDays(1).atStartOfDay();
You can simplify this by SQL Date functions. FYI

2021-01-29 12:40 UTC, Max-Pochepets commented on src/main/java/ua/com/conductor/dao/impl/MovieSessionDaoImpl.java
> +    }
You don't need it in the scope of this task

2021-01-29 12:40 UTC, Max-Pochepets commented on src/main/java/ua/com/conductor/service/impl/MovieSessionServiceImpl.java
> +    }
same

2021-01-29 13:04 UTC, Max-Pochepets approved these changes
👍

2021-02-01 17:54 UTC, KseniiaMakarova requested changes
let's fix travis

2021-02-01 17:54 UTC, KseniiaMakarova commented on src/main/java/ua/com/conductor/Application.java
> +        movieSessionService.findAvailableSessions(1L, LocalDate.now())
let's use `movie.getId()` instead

2021-02-01 17:54 UTC, KseniiaMakarova commented on src/main/java/ua/com/conductor/model/MovieSession.java
> +    @JoinColumn(name = "cinema_hall")
```suggestion
    @JoinColumn(name = "cinema_hall_id")
```

2021-02-01 18:05 UTC, KseniiaMakarova approved these changes

2021-02-01 18:12 UTC, merged