hw was implemented
Mandybur800/StandUpLite pull request #3
Opened 2021-02-02 08:22 UTC by Mandybur800

2021-02-02 09:46 UTC, IvanLuchkin requested changes

2021-02-02 09:46 UTC, IvanLuchkin commented on src/main/java/ua/com/conductor/dao/impl/UserDaoImpl.java
> +            getByEmailQuery.setParameter("email", email);
Can be written in one line, but up to you

2021-02-02 09:46 UTC, IvanLuchkin commented on src/main/java/ua/com/conductor/model/User.java
> +@Table(name = "user")
It's better to use plural for table names. Moreover, such name for the table may conflict with internal MySQL table for users

2021-02-02 09:46 UTC, IvanLuchkin commented on src/main/java/ua/com/conductor/service/impl/AuthenticationServiceImpl.java
> +        String hashPassword = HashUtil.hashPassword(password, salt);
```suggestion
        String hashedPassword = HashUtil.hashPassword(password, salt);
```

2021-02-02 10:27 UTC, IvanLuchkin approved these changes

2021-02-02 17:00 UTC, dmytro-hryhoruk requested changes

2021-02-02 17:00 UTC, dmytro-hryhoruk commented on src/main/java/ua/com/conductor/dao/impl/UserDaoImpl.java
> +                    User.class).setParameter("email", email).uniqueResultOptional();
```suggestion
            return session
                  .createQuery("FROM User WHERE email = :email", User.class)
                  .setParameter("email", email)
                  .uniqueResultOptional();
```

2021-02-02 17:00 UTC, dmytro-hryhoruk commented on src/main/java/ua/com/conductor/service/impl/AuthenticationServiceImpl.java
> +            throw new AuthenticationException("Incorrect login");
let's not make the life of some hackers easier) 
Let's not refactor this method the way so we are throwing AuthenticationException only once and only with the message: 
"Incorrect login or password"; for example you can user optionalUser.isPresent() with &&

2021-02-02 17:00 UTC, dmytro-hryhoruk commented on src/main/java/ua/com/conductor/service/impl/AuthenticationServiceImpl.java
> +        return user;
checklist

2021-02-03 10:58 UTC, dmytro-hryhoruk approved these changes

2021-02-03 10:58 UTC, merged